package registry_test

import (
	"encoding/json"
	"io/fs"
	"sort"
	"testing"

	registry "github.com/veildawn/ai-model-registry"
)

// all.json is a generated copy of every other file here, which makes it the one
// thing in this repository that can be WRONG rather than merely out of date: a
// consumer fetching the bundle instead of the 21 files gets whatever it says,
// and nothing about a stale bundle looks broken — the sync succeeds, the models
// are all there, and some of the prices are from last week.
//
// scripts/bundle.py --check guards the committed bytes in CI. These tests guard
// the meaning, in the build, so a consumer's `go test` catches the drift even if
// the bundle was regenerated by something other than the script.

// bundleDoc mirrors all.json. Files is keyed by the registry-relative path of
// the file it carries, so the bundle is addressed exactly like the directory.
type bundleDoc struct {
	Version     int                        `json:"version"`
	GeneratedBy string                     `json:"generated_by"`
	Files       map[string]json.RawMessage `json:"files"`
}

func readBundle(t *testing.T) bundleDoc {
	t.Helper()
	raw, err := registry.Files.ReadFile("all.json")
	if err != nil {
		t.Fatalf("all.json is not embedded: %v", err)
	}
	var doc bundleDoc
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("all.json: %v", err)
	}
	if len(doc.Files) == 0 {
		t.Fatal("all.json carries no files")
	}
	return doc
}

// canonical re-encodes a JSON document with its object keys sorted, so two
// documents that state the same thing compare equal whatever order or
// indentation either one was written in. What matters is that a consumer
// parsing the bundle sees the same values, not that the bytes match.
func canonical(t *testing.T, label string, raw []byte) string {
	t.Helper()
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("%s: %v", label, err)
	}
	out, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("%s: %v", label, err)
	}
	return string(out)
}

// TestBundleCarriesEveryFileVerbatim is the anti-drift guard. Every path in the
// repository must appear in the bundle with the same content, and the bundle
// must carry nothing else — a provider deleted from the directory but left in
// all.json would keep being published to every consumer that fetches the
// bundle.
func TestBundleCarriesEveryFileVerbatim(t *testing.T) {
	doc := readBundle(t)

	paths, err := fs.Glob(registry.Files, "providers/*.json")
	if err != nil {
		t.Fatal(err)
	}
	paths = append(paths, "index.json")
	sort.Strings(paths)

	onDisk := make(map[string]bool, len(paths))
	for _, path := range paths {
		onDisk[path] = true
		bundled, ok := doc.Files[path]
		if !ok {
			t.Errorf("%s exists but all.json does not carry it; regenerate with "+
				"python3 scripts/bundle.py", path)
			continue
		}
		body, err := registry.Files.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if want, got := canonical(t, path, body), canonical(t, "all.json["+path+"]", bundled); want != got {
			t.Errorf("all.json disagrees with %s; regenerate with "+
				"python3 scripts/bundle.py\n  file:   %s\n  bundle: %s", path, want, got)
		}
	}
	for path := range doc.Files {
		if !onDisk[path] {
			t.Errorf("all.json carries %q, which is not a file in this repository; "+
				"regenerate with python3 scripts/bundle.py", path)
		}
	}
}

// TestBundleVersionMatchesTheIndex keeps the bundle's self-description honest.
// A consumer rejects a version it does not understand before parsing anything
// inside, so a bundle stating a version its contents do not have would be read
// by exactly the clients that should have refused it.
func TestBundleVersionMatchesTheIndex(t *testing.T) {
	doc := readBundle(t)
	var idx struct {
		Version int `json:"version"`
	}
	body, err := registry.Files.ReadFile("index.json")
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(body, &idx); err != nil {
		t.Fatal(err)
	}
	if doc.Version != idx.Version {
		t.Errorf("all.json version = %d, index.json version = %d", doc.Version, idx.Version)
	}
	if doc.GeneratedBy != "scripts/bundle.py" {
		t.Errorf("all.json generated_by = %q, want scripts/bundle.py — the bundle "+
			"names its generator so nobody mistakes it for a hand-edited file",
			doc.GeneratedBy)
	}
}

// TestBundlePublishesTheSameModelSet walks both routes to the same question —
// which (provider, model) ids does this registry publish, with which facts —
// and requires one answer. The file comparison above would already catch a
// difference; this one states what a difference COSTS, in the vocabulary a
// consumer reads, and fails with the ids rather than with a blob of JSON.
//
// Ids are expanded through the variant suffixes, because that is the set a
// consumer indexes: a family whose suffix list moved in one place and not the
// other publishes a different catalog while every file still parses.
func TestBundlePublishesTheSameModelSet(t *testing.T) {
	doc := readBundle(t)

	fromDisk := map[string]string{}
	fromBundle := map[string]string{}

	paths, err := fs.Glob(registry.Files, "providers/*.json")
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range paths {
		body, err := registry.Files.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		collectPublished(t, fromDisk, path, body)
	}
	for path, body := range doc.Files {
		if path == "index.json" {
			continue
		}
		collectPublished(t, fromBundle, "all.json:"+path, body)
	}

	if len(fromDisk) == 0 {
		t.Fatal("the provider files publish no models")
	}
	for key, want := range fromDisk {
		got, ok := fromBundle[key]
		if !ok {
			t.Errorf("all.json does not publish %q", key)
			continue
		}
		if got != want {
			t.Errorf("%q differs between all.json and its provider file:\n  file:   %s\n  bundle: %s",
				key, want, got)
		}
	}
	for key := range fromBundle {
		if _, ok := fromDisk[key]; !ok {
			t.Errorf("all.json publishes %q, which no provider file does", key)
		}
	}
	t.Logf("%d published (provider, model) ids, identical both ways", len(fromDisk))
}

// publishedFile is the provider file as a consumer reads it, with each model
// left as raw JSON so EVERY field it carries takes part in the comparison —
// including ones no struct here has been taught about yet, which are exactly
// the fields a hand-edited bundle would silently differ in.
type publishedFile struct {
	Name         string            `json:"name"`
	DisplayName  string            `json:"display_name"`
	ListPrices   bool              `json:"list_prices"`
	HiddenModels []string          `json:"hidden_models"`
	Models       []json.RawMessage `json:"models"`
}

// collectPublished records every (provider, model) this file publishes, keyed
// as the consumer keys it, against the full set of facts the id inherits.
func collectPublished(t *testing.T, into map[string]string, label string, body []byte) {
	t.Helper()
	var prov publishedFile
	if err := json.Unmarshal(body, &prov); err != nil {
		t.Fatalf("%s: %v", label, err)
	}
	for _, raw := range prov.Models {
		var m struct {
			Model    string `json:"model"`
			Variants *struct {
				Suffixes []string `json:"suffixes"`
			} `json:"variants"`
		}
		if err := json.Unmarshal(raw, &m); err != nil {
			t.Fatalf("%s: %v", label, err)
		}
		// The file-level facts every one of its models inherits, plus the
		// entry itself, canonicalised so key order cannot register as a change.
		facts := prov.DisplayName + "|" +
			canonical(t, label, mustMarshal(t, prov.ListPrices)) + "|" +
			canonical(t, label, mustMarshal(t, prov.HiddenModels)) + "|" +
			canonical(t, label, raw)

		ids := []string{m.Model}
		if m.Variants != nil {
			ids = ids[:0]
			for _, suffix := range m.Variants.Suffixes {
				ids = append(ids, m.Model+suffix)
			}
		}
		for _, id := range ids {
			key := prov.Name + "\x00" + id
			if _, dup := into[key]; dup {
				t.Errorf("%s: %q is published twice", label, key)
			}
			into[key] = facts
		}
	}
}

func mustMarshal(t *testing.T, v any) []byte {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return raw
}
